In [1]:
backward_array = function (x, y, Ndims)
    c = Array{Float32}(undef, Ndims, Ndims)
    for j in 1:Ndims
        for i in 1:Ndims
            c[i, j] = x[i, j] * y[i, j]
        end        
    end
    return c
end

forward_array = function (x, y, Ndims)
    c = Array{Float32}(undef, Ndims, Ndims)
    for i in 1:Ndims
        for j in 1:Ndims
            c[i, j] = x[i, j] * y[i, j]
        end        
    end
    return c
end

backward_array3 = function (x, y, Ndims)
    c = Array{Float32}(undef, Ndims, Ndims, Ndims)
    for k in 1:Ndims
        for j in 1:Ndims
            for i in 1:Ndims
                c[i, j, k] = x[i, j, k] * y[i, j, k]
            end
        end
    end
    return c
end

forward_array3 = function (x, y, Ndims)
    c = Array{Float32}(undef, Ndims, Ndims, Ndims)
    for i in 1:Ndims
        for j in 1:Ndims
            for k in 1:Ndims
                c[i, j, k] = x[i, j, k] * y[i, j, k]
            end
        end
    end
    return c
end

Ndims = 2^10
a = rand(Float32, Ndims, Ndims)
b = rand(Float32, Ndims, Ndims)
@time forward_array(a, b, Ndims)
@time backward_array(a, b, Ndims)

Ndims = 2^7
a = rand(Float32, Ndims, Ndims, Ndims)
b = rand(Float32, Ndims, Ndims, Ndims)
@time forward_array3(a, b, Ndims)
@time backward_array3(a, b, Ndims)

  0.025458 seconds (35.23 k allocations: 5.760 MiB, 71.46% compilation time)
  0.014418 seconds (14.01 k allocations: 4.711 MiB, 96.58% compilation time)
  0.057718 seconds (57.78 k allocations: 10.823 MiB, 33.66% compilation time)
  0.021441 seconds (20.36 k allocations: 9.003 MiB, 9.91% gc time, 86.04% compilation time)


128×128×128 Array{Float32, 3}:
[:, :, 1] =
 0.228055   0.314276    0.356018     …  0.0345603   0.131787   0.0559931
 0.0464213  0.438026    0.0948839       0.00188949  0.648621   0.0173135
 0.0353337  0.489601    0.482377        0.142315    0.274755   0.614353
 0.164469   0.476216    0.341347        0.599906    0.264556   0.0129104
 0.642619   0.0163238   0.000889247     0.183216    0.180771   0.2549
 0.524028   0.164618    0.0211358    …  0.0957788   0.0328978  0.278503
 0.0787391  0.0983511   0.0604335       0.385937    0.0929591  0.895394
 0.0838667  0.0152937   0.0300206       0.0960976   0.340677   0.0159617
 0.242822   0.248215    0.107765        0.00780001  0.219614   0.0422761
 0.320521   0.00843421  0.0400316       0.380292    0.163417   0.64969
 ⋮                                   ⋱  ⋮                      
 0.130773   0.0810182   0.0141868       0.734986    0.0963974  0.14842
 0.229385   0.534213    0.239902     …  0.799217    0.166792   0.739803
 0.127089   0.568686    0.05

In [6]:
N = 10^8
h = 2π/N
y = 1.0 + 0.0im
@time for i in 1:N
  y += h * im * y
end
y

  6.614943 seconds (500.00 M allocations: 11.921 GiB, 1.20% gc time)


1.0000001973920172 + 8.725669089740029e-15im

In [5]:
function main()
    N = 10^8
    h = 2π/N
    y = 1.0 + 0.0im
    for i in 1:N
      y += h * im * y
    end
    y
end

@time main()

  0.359339 seconds


1.0000001973920172 + 8.725669089740029e-15im

In [ ]:
N = 10^8
a = rand(N)
b = rand(N)
c = rand(N)
d = rand(N)

#================================================================
# 改良前 メモリ消費が大きい
s = Array{Float64}(undef, N)
mysum0 = function (a, b, c, d)
    s = a + b + c + d
end
@time mysum0(a, b, c, d)
================================================================#
# 改良後 ドット構文使用
t = Array{Float64}(undef, N)
mysum1! = function (a, b, c, d)
    @. t = a + b + c + d
end
@time mysum1!(a, b, c, d)

In [6]:
import Pkg

c = ["Tidier", "DataFrames", "MacroTools"]
Pkg.add(c)

using  Tidier
using DataFrames
using MacroTools

df = DataFrame(
    x = rand(5),
    y = rand(5)
)

df = DataFrame(x = Int32[], y = Int32[])
new_row = (10, 20)
push!(df, new_row)

df =
@chain DataFrame(x = Int32[], y = Int32[]) begin
    push!([10, 20])
    @aside @show _
    push!([20, 1])
end

x = [1 2; 3 4; 5 6;;; 11 12; 13 14; 15 16;;; 111 222; 333 444; 555 666]
df = DataFrame(x)

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.10/Project.toml`
  No Changes to `~/.julia/environments/v1.10/Manifest.toml`


var"##230" = 1×2 DataFrame
 Row │ x      y
     │ Int32  Int32
─────┼──────────────
   1 │    10     20


ArgumentError: ArgumentError: 'Array{Int64, 3}' iterates 'Int64' values, which doesn't satisfy the Tables.jl `AbstractRow` interface

In [4]:
z = 0
x = 0
x / z

NaN

In [23]:
x = 1
y = 0
z = 0
a = [
    x (x / y);
    y (y / z);
]

a .> 1




2×2 BitMatrix:
 0  1
 0  0

In [64]:
Ndims = 2^8
Pdims = 3

in_out = rand(Bool, Ndims, Ndims, Pdims)
println(size(in_out))

loop_f1 = function (org_arr, Ndims)
    for j in 1:Ndims
        for i in 1:Ndims
            subject_cal_arr[i, j] = prod(org_arr[i, j, :])
        end
    end
end

vec_f1 = function (org_arr)
    subject_cal_arr .= prod(org_arr, dims = 3)
end


@time loop_f1(in_out, Ndims)
@time vec_f1(in_out)

(256, 256, 3)
  0.021451 seconds (73.88 k allocations: 4.580 MiB, 84.48% compilation time)
  0.002936 seconds (8.58 k allocations: 668.711 KiB, 99.10% compilation time)


256×256 Matrix{Bool}:
 0  0  0  0  0  0  0  0  0  0  0  1  0  …  1  0  0  0  0  1  0  0  1  0  0  0
 0  1  0  0  0  0  0  0  0  1  0  0  1     0  0  0  0  0  0  0  1  0  0  0  0
 0  0  0  0  0  0  0  0  0  1  0  0  0     0  1  0  1  0  0  0  1  0  1  0  0
 0  0  0  0  0  0  0  0  0  0  1  1  0     0  0  1  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  0  0  0  0  1  0  0     0  1  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  1  0  0  0  0  0  0  0  …  0  0  1  0  0  0  1  0  0  0  0  0
 0  0  1  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  1
 0  0  1  0  0  0  0  0  0  0  1  0  1     0  1  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  1  0  0  1  0  1  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  1
 ⋮              ⋮              ⋮        ⋱     ⋮              ⋮              ⋮
 1  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  1  0
 0  0  1  0  1  0  0  0  0  0  0  0  0    

In [13]:
x = Vector{Int32}(1:5)
y = x .+ 1

5-element Vector{Int64}:
 2
 3
 4
 5
 6

In [ ]:
a = [1, 1, 3.5, 3, 5, 1]
a_unq = unique(a)
n = length(a_unq)
b = Array{Float32}(undef)
for i in a_unq
    b[i] = i # 配列のインデックスが整数でないのでエラー
    println(b[i])
end

In [24]:
import Pkg
Pkg.add("Chain")
using Chain

a = (Int32)[1, 2, 3]
b = (Int32)[4, 5, 6]

c = append!(a, b)

fill(Vector(1:3), 5)

f1 = function (N)
    a = Vector{Int32}(undef, 0)
    for i in 1:N
        a = append!(a, fill(i, 5))
    end
end

f2 = function (N)
    a = Vector{Int32}(undef, 0)
    for i in 1:N
        tmp = a
        a = append!(tmp, fill(i, 5))
    end
end

# for i in 1:3
#     tmp = a
#     a = append!(tmp, fill(i, 5))
# end

N = 2^8
#  どちらでも速さは変わらない
@time f1(N)
@time f2(N)

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.10/Project.toml`
  No Changes to `~/.julia/environments/v1.10/Manifest.toml`


  0.007024 seconds (8.79 k allocations: 663.516 KiB, 99.73% compilation time)
  0.006437 seconds (8.76 k allocations: 661.250 KiB, 99.74% compilation time)


In [28]:
import Pkg
Pkg.add("Chain")
using Chain

n_y = 3
a = Vector{Int32}(1:n_y)
b = Vector{Int32}(undef, 0)
for _ in 1:4
    b = append!(b, a)
end
println(b)
# @chain 1 begin
#     + 1
#     + 1
# end


   Resolving package versions...
  No Changes to `~/.julia/environments/v1.10/Project.toml`
  No Changes to `~/.julia/environments/v1.10/Manifest.toml`


Int32[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


In [2]:
import Pkg

c = ["Tidier", "DataFrames", "NaNStatistics"]
Pkg.add(c)

using Tidier
using DataFrames
using NaNStatistics

# df_x = [1, 1, 2, 2, 3, 3]
# df_y = [1, 2, 1, 2, 1, 2]
# in_out_df = DataFrame(
#     x_index = df_x,
#     y_index = df_y
# )
# v_arr = Array{Int32}(undef, length(unique(df_x)), length(unique(df_y)))
# println(v_arr)
# for x in 1:3
#     for y in 1:2
#         v_arr[x, y] = x * y
#     end
# end
# println(v_arr)

# a_arr = (Int32)[
#     11 12 13;
#     21 22 23;
#     31 32 33;
#     41 42 43
# ]
# a_arr
# (n_x, n_y) = size(a_arr)

# df_y = Vector{Int32}(undef, 0)
# rep = Vector{Int32}(1:n_y)
# for _ in 1:n_x
#     df_y = append!(df_y, rep)
# end

# df_y = repeat(Vector{Int32}(1:n_y), inner = [n_x])
# @show df_y
# # df_x = Vector{Int32}(undef, 0)
# # for i in 1:n_x
# #     df_x = append!(df_x, fill(i, n_y))
# # end

# df_x = repeat(Vector{Int32}(1:n_x), outer = [n_y])
# @show df_x
# # df_y = Vector{int32}(undef, 0)
# # rep = Vector{int32}(1:n_y)
# # for _ in 1:n_x
# #     df_y = append!(df_y, rep)
# # end

# colnames = 
# @chain Vector{Int32}(1:n_y) begin
#     string.()
#     string.("y", _)
# end
# @show colnames

# # colnames = ["first", "second", "third"]

# # df_long = 
# # @chain a_arr begin
# #     DataFrame(colnames)
# #     @filter(y1 == 11)
#     # @filter(first == 11)
#     # @pivot_longer(, name_to = y, values_to = sub)
# # end

# # df_long =
# # @chain a_arr begin
# #     DataFrame(:auto)
# #     rename!([1 => :c_1st, n_y => :c_last])
# #     @pivot_longer(c_1st:c_last, name_to = y, values_to = value)
# # end
# # @show df_long

# # df_long =
# # @chain a_arr begin
# #     DataFrame(:auto)
# #     # rename!([1 => :c_1st, n_y => :c_last])
# #     # @pivot_longer(c_1st:c_last, name_to = y, values_to = cal)
# #     @pivot_longer(starts_with("x"), names_to = y, values_to = cal)
# #     insertcols!(:index_x => df_x)
# #     insertcols!(:index_y => df_y)
# #     @select(-y)
# # end

# # poly_ids = unique(df_long.index_y)
# # for p in poly_ids
# #     edge =
# #     @chain df_long begin
# #         filter(row -> row.index_y == p, _)
# #         @aside @show _
# #     end
# # end

# # winding_angle = zeros(Float32, n_x, n_y)

# # データフレームを作成
# df = DataFrame(
#     index_x = [1, 10, 8, 4]
# )

# # 定数
# dd = 10
# x_min = 0

# @chainマクロを使ったパイプライン処理
# df = 
# @chain df begin
#     @mutate(xx = (!!x_min + (index_x - 1) * !!dd))
# end


# df2 = DataFrame(
#     index_x = [10, 100, 40, 80]
# )

# df3 = 
# @chain df begin
#     @bind_rows(df2, id = "tmp_id")
#     # transform!(:tmp_id => plus)
#     # @mutate(id = tmp_id)
#     # @mutate(id = (Int32)(tmp_id + plus_id))
#     @mutate(id = (Int32)(tmp_id + !!dd))
#     @select(-tmp_id)
# end

# a = [1, 2, NaN, 5, 7, NaN32]
# b = (a .> 3)

# a = [NaN, NaN, NaN]
# nansum(a)

# x =zeros(Float32, 3)
y = [
    0.1 0.45
    5 0.3
    0.25 1.2
]
# sum(y[:,i] for i in 1:2)

# # a = [1.0 1.0; 2.0 2.0; 3.0 3.0;;; 10 10; 21 20; 30 30;;; 100 100; 200 200; 300 301]
# sum(a[:, :, i] for i in 1:3)

# acos(453.46246 / 453.46243)

sum([1.787526, 2.3818636, 0.7336252, 0.6850935, 0.25532898, 0.49341002, 0.21346754, 0.71969044])

# replace!(y, NaN => 0)
# y
# y[y .> 1] .= 1
# y

@chain y begin
     z = _
    _[_ .> 1] .= 1
end
z
w = similar(z)
w .= acos.(z)
w


const b = size(y, 1)
b

ll = convert(Float32, 99999)

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.10/Project.toml`
  No Changes to `~/.julia/environments/v1.10/Manifest.toml`


99999.0f0